name: "Setup node and install Dependencies"
description: "setup node, cache Dependencies and install"
runs:
  using: composite
  steps:
    - name: "Setup Nodejs"
      uses: actions/setup-node@v4
      with:
          node-version: 22

    - name: Cache Dependencies
      uses: actions/cache@v4
      id: cache 
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} 

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install

    
      shell: bash
