name: Build
on: push
jobs:
    preview:
        runs-on: ubuntu-latest
        steps:
          # - name: Get Code 
          #   run: |
          #       echo "Cloning repository"
          #       echo "${{toJson(github)}}"
          #       git clone https://github.com/${{github.repository}}.git myfiles  
          #       cd myfiles && ls
          
          ## Alternative simple method##
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: 22
            - name: Print Node Version 
              run: node -v 
            - name: Install Dependencies
              run: npm install 
            - name: Run Preview 
              run: npm run preview 
            - name: Completed Job 
              run: echo "Preview Completed" 
              