name: Build
on: 
    # push:
    #   branches: 
    #     - main
    #     - 'feature/**'
    #   paths-ignore:
    #     - README.md
    #     - '.github/workflows/*'
    workflow_dispatch:
      

jobs:
    preview:
        runs-on: ubuntu-latest
        steps:
          # - name: Get Code 
          #   run: |
          #       echo "Cloning repository"
          #       echo "${{toJson(github)}}"
          #       git clone https://github.com/${{github.repository}}.git myfiles  
          #       cd myfiles && ls
          
          ## Alternative simple method##
            - name: Get Code
              uses: actions/checkout@v4
              
            - name: Install Node
              uses: ./.github/actions/setupnode

            - name: Run Preview 
              run: |
                  npm run preview &
                  PREVIEW_PID=$!
                  sleep 5   
                  kill $PREVIEW_PID  
            - name: Completed Job 
              run: echo "Preview Completed" 

    Build: 
        needs: preview
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4

            - name: Install Node
              uses: ./.github/actions/setupnode  

            - name: Build The Project
              run: npm run build

            - name: Upload Dist Artifact
              uses: actions/upload-artifact@v4 
              with:
                name: dist-files
                path: dist
                 
    Deploy:
        needs: Build
        runs-on: ubuntu-latest
        steps:
          - name: Download Dist Artifact
            uses: actions/download-artifact@v4 
            with:
                name: dist-files
                path: dist
          - name: Deploy Code
            run: |
              echo "Deploying Below File"
              ls dist
              echo "deployment Completed"